### ISSUE TITLE
Product stock not updating in the DB after purchase | productScreen keeping the same stock after purchase.

### ISSUE THREAD

**Issue by Pablets** [bradtraversy/proshop_mern#102]
## Product stock not updating in the DB after purchase

 - After a correct purchase from a user the countInStock property of each items its not updating the correct stock.

**Comment by basir** [comment]
Decreasing count in stock is part of a bigger story which is inventory management. we need to handle adding products to the inventory and removing products on placing orders. This feature has been noted for the next updates.
