### ISSUE TITLE
An easier way to add/remove from the cart

### ISSUE THREAD

**Issue by aboubacarmsr** [bradtraversy/proshop_mern#105]
This is not really an issue but i was wondering if there was an easier way to do this.

Since the ADD TO CART button is in the ProductScreen which already has all the data of the product, maybe it would be easier if the CART_ADD_ITEM action received the product as a parameter directly from that screen instead of passing the id and the quantity through the url then make another request to the DB to get the product.

Sorry, my English is not that good but this is what i mean : 

`const { isLoading, error, product } = useSelector((state) => state.productDetails);
 const { cartItems } = useSelector((state) => state.cart);

const productExists = cartItems.find((item) => item._id === id);
  const addToCartHandler = () => {
    if (productExists) {
      dispatch(deleteFromCart(product));
    } else if (!productExists && product.countInStock > 0) {
      dispatch(addToCart(product));
    }
    else {
        alert('This product is sold out.')
    }
  };`

Using this method won't redirect you to the cart screen each time you add an article because i think that may annoy some people.

I did it this way and it is working. Since i have not finish all the project yet, i don't know if it will break later

**Comment by basir** [comment]
about the first issue, I would say that you may need to check again product availability before adding it to the cart. we did not check that at the moment but it is a room have such type of checks.
why do you delete a product from the cart if it already exists? you should update the item count in the cart like what we did in the code.
