### ISSUE TITLE
Change the currency of PayPal sdk to AUD

### ISSUE THREAD

**Issue by SuneelGiri** [bradtraversy/proshop_mern#107]
I am surprised it hasn't been asked already. How to change the currency to AUD or any other? I tried adding &currency=AUD in script, checked all around in paypal but can't seems to fix it. Please let me know. Thanks!

**Comment by aashiqahmed98** [comment]
> I am surprised it hasn't been asked already. How to change the currency to AUD or any other? I tried adding &currency=AUD in script, checked all around in paypal but can't seems to fix it. Please let me know. Thanks!

You can create new account inside paypal sandbox with AUD currency,by default it's USD

**Comment by SuneelGiri** [comment]
@aashiqahmed98 nope doesn't work dude. Please try it yourself once.

**Comment by aashiqahmed98** [comment]
@SuneelGiri did you have the location as 'Australia ',For me it worked as I chose 'in' for India

**Comment by SuneelGiri** [comment]
@aashiqahmed98 Yes I did. so, what was your process? I went to Apps & Credentials>there is sandbox /live> i clicked live and created one. There is no location choice. Have you tried live version?

**Comment by SuneelGiri** [comment]
@aashiqahmed98 I found the solution. our Paypal button also needs to be updated.
So, if the currency is AUD, first we add &currency=AUD at the end of the script
then, inside PaypalButton, we add currency="AUD"
:)
