### ISSUE TITLE
304 responses

### ISSUE THREAD

**Issue by JEMasonMedia** [bradtraversy/proshop_mern#11]
Any access to products results in a 304 status
![2020-10-04_11-02](https://user-images.githubusercontent.com/42191306/95020492-28a50680-0631-11eb-924a-265aec2ab574.png)

**Comment by JEMasonMedia** [comment]
This may be a non issue. Most of the responses do not set a status, so I would assume the 304 is standard. 

[https://restfulapi.net/http-status-codes/](url)

`res.json({ products, page, pages: Math.ceil(count / pageSize) }) `

**Comment by bradtraversy** [comment]
304 just means not modified. Nothing has changed since the last request. More info here

https://httpstatuses.com/304

**Comment by GeorgiosAlexopoulos** [comment]
If you stop the server , refresh the browser , restart the server , check network>products, the response is 200 as shown in the video
