### ISSUE TITLE
Take Payments in INR 

### ISSUE THREAD

**Issue by B4xAbhishek** [bradtraversy/proshop_mern#111]
Sir, I tried to accept payment in INR, used the same Paypal Client key provided by Paypal India but while paying the amount is displayed as US dollars (in the Paypal window). How can I change that to INR? 
I have changed the rest to INR and tried &currency=INR
Please help

**Comment by krizando** [comment]
Look up closed issues. There is an answer:
https://github.com/bradtraversy/proshop_mern/issues/107

**Comment by B4xAbhishek** [comment]
Thank you for your response
