### ISSUE TITLE
The search Text should clear up ,after the route changes or clicking back to HomePage 

### ISSUE THREAD

**Issue by aashiqahmed98** [bradtraversy/proshop_mern#115]
The search keyword on the search Box component resided throught the process of the flow of the App.It should be cleared after clicking some product or 'Proshop' banner text.

**Comment by tanishqdaiya** [comment]
# Not Necessary
There are many sites like YouTube who have search box component that doesn't get cleared when redirecting to home page.  
However if you want to do this, It's simple.  

It's still a good idea and can be implemented easily.
