### ISSUE TITLE
app crashed when running the server and client using 'npm run dev'

### ISSUE THREAD

**Issue by AshTech25** [bradtraversy/proshop_mern#116]
Error: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
[nodemon] app crashed
![Github error](https://user-images.githubusercontent.com/38139351/109915380-8e2a1b80-7cd3-11eb-86d5-a4c80b39e1fe.png)
 - waiting for file changes before starting...

**Comment by tanishqdaiya** [comment]
# Environment Variables
Did you make an ENV file in the root directory?

**Comment by tanishqdaiya** [comment]
# Make an ENV File
Make an ENV File in root directory and fill the values.

**Comment by basir** [comment]
create a file named .env and enter this line:
MONGO_URI=your db connection in mongodb atlas

then restart the server to fix this issue.

please ask this type of questions in Udemy Q/A. Only create an issue for an error in the repo not in your code.
