### ISSUE TITLE
A few issues with the Cart

### ISSUE THREAD

**Issue by badgersmans** [bradtraversy/proshop_mern#12]
I've noticed a few issues with the Cart:

Cart items are not associated to a user on the frontend.

You could add an item to cart even if you're not logged in, which is weird.
If you add an item to cart, and you log in, it's the same cart items, and if you log out, nothing changes. And if you log into a different user, and check the cart items, it is still the same cart items.

I think that it would make more sense if the cart item was associated to a user, so that every user has their own cart items.

That would be great!

**Comment by HMayotte** [comment]
I 100% agree on this one1

**Comment by bradtraversy** [comment]
Yeah, I see what you meant. We initially wanted people to be able to add to cart without being logged in. Keep in mind, this is a course project. I would have to re-do a lot of the course to implement. 

I may add a section at the end to do this. Then I will update the repo.

**Comment by adam-spice** [comment]
The easiest thing to do would be add CART_RESET that fires when someone logs out or pays for an order. 

The harder thing to do would be to have a cart collection in the DB that contains the items and is linked to a user. This is what I am working on now as I want to be able to do abandoned cart emails in the end,

**Comment by badgersmans** [comment]
yea was thinking the same, maybe the user scheme should reference a cart items schema...

so you would have a user object with an array of cart items... quite possibly the solution..

and yes, should clear the cart state when logout or paid

**Comment by adamwinzdesign** [comment]
There's also an issue with the cart and deleting items, in lecture 35 I believe.  If the user goes to the cart via add item to cart, the item id and quantity are included in the url.  However, if the user then deletes the item from the cart, state and localStorage are adjusted correctly, but if the user then refreshes the page, the item is then re-added to the cart because the url still has the item id and quantity included in it.  I'd love to be able to fix this but I don't know where to begin.

**Comment by Legitao** [comment]
@adamwinzdesign My solution is not using path like `cart/:id?qty=1` and not invoking dispatch in CartScreen, instead only use `/cart` and invoke dispatch in the Add to Cart button's onClick handler in the ProductDetailsScreen. 
Here is my code for reference[https://github.com/Legitao/my-nba-store-frontend/commit/1985fff61b462b80d3e65266c42b042145c88ee7](url)
