### ISSUE TITLE
TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function. How to fix this?

### ISSUE THREAD

**Issue by MarkVed17** [bradtraversy/proshop_mern#122]
![err](https://user-images.githubusercontent.com/59828215/110624444-3a806c00-81c4-11eb-921b-07a2b1780138.png)

**Comment by basir** [comment]
hello there,
it is an issue in reducers that you defined in your project. please ask it in udemy Q/A to get an answer. also check this thread to see why you get this error.
Only create an issue here if you find an error in this repo not in your code.
