### ISSUE TITLE
How to assign a url to a order?

### ISSUE THREAD

**Issue by talmax1124** [bradtraversy/proshop_mern#123]
Hello, I am using uploadcare for allowing users to add their files since I don't have much experience in react. I just want to know step by step how to assign a URL given by the service already and assign it to the order so that way I can see the URL later on. 

Any Idea? I can set up a live share in vscode if you need to see. Thanks.

**Comment by talmax1124** [comment]
What I mean by this, how to assign a variable that contains a URL to the orderID so that whenever I come back, the URL stays stored to that order.

**Comment by basir** [comment]
your order url is like this: https://youdomain.com/order/orderid
why do you want to save it in the db?

**Comment by talmax1124** [comment]
> your order url is like this: https://youdomain.com/order/orderid
> 
> why do you want to save it in the db?

@basir Hello. So I am using uploadcare to get file uploads since I don't know how to implement something else. Once a user uploads, they put a param that links to a CDN-URL or a link to download. I want to link that URL that they provide to that order so that I can re-visit it or the user. 

So basically, I get the URL that the  uploder gives from the cdn and assign it to a button to open it. But once I reload, the URL goes away because its not saved to the database.

**Comment by basir** [comment]
you can add a new String field like cdnUrl to the order and then call an ajax to put it in that order.

**Comment by talmax1124** [comment]
I don't know ajax. Is there a link or example?

**Comment by talmax1124** [comment]
Any specific files I need to edit except the model? @basir @bradtraversy

**Comment by talmax1124** [comment]
I want to specify that it is in the order screen where the user pays that screen, its optional so do I need to modify the order controller for something like if User Uploaded. Can you review my repo to understand it.

**Comment by talmax1124** [comment]
Repo URL: https://github.com/talmax1124/cduoshop/

**Comment by basir** [comment]
hello there,
please only create issues for errors in this repo, not your own code. ask your issues in Udemy Q/A.
