### ISSUE TITLE
backend seeder problem in importing the data 

### ISSUE THREAD

**Issue by Abdulh664** [bradtraversy/proshop_mern#125]
Sir, I'm having a problem inserting data into the database I have done my best to solve the issue but nothing happened.  need help 
![image_2021-03-19_100711](https://user-images.githubusercontent.com/80402956/111733948-e1d36200-889a-11eb-8dbc-ef53e56a0951.png)

**Comment by talmax1124** [comment]
Share the full error @Abdulh664

**Comment by Abdulh664** [comment]
![Screenshot (19)](https://user-images.githubusercontent.com/80402956/111834149-fc4a2180-8914-11eb-9fa1-1de3dc9ca3ed.png)



> Share the full error @Abdulh664

**Comment by Abdulh664** [comment]
I remove the timestamps: true from "userModel" , "productModel", and "orderModel" then its work and show that data is imported,  can you please tell me that what is the timestamp is about and why it is showing an error for me when I'm using it

![image_2021-03-20_020352](https://user-images.githubusercontent.com/80402956/111841924-88ae1180-8920-11eb-97d2-a7f9b55568f6.png)

**Comment by basir** [comment]
hello there,
please only create issues for errors in this repo, not your own code. ask your issues in Udemy Q/A.

**Comment by talmax1124** [comment]
So, timestamps are so that the database know which one to display first, ex: the reviews

**Comment by talmax1124** [comment]
Use this instead },
  {
    timestamps: true,
  }

**Comment by talmax1124** [comment]
Use this code: 
import mongoose from 'mongoose'

const reviewSchema = mongoose.Schema(
  {
    name: { type: String, required: true },
    rating: { type: Number, required: true },
    comment: { type: String, required: true },
    user: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
      ref: 'User',
    },
  },
  {
    timestamps: true,
  }
)

const productSchema = mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
      ref: 'User',
    },
    name: {
      type: String,
      required: true,
    },
    image: {
      type: String,
      required: true,
    },
    brand: {
      type: String,
      required: true,
    },
    category: {
      type: String,
     
    },
    description: {
      type: String,
  
    },
    reviews: [reviewSchema],
    rating: {
      type: Number,
      required: true,
      default: 0,
    },
    numReviews: {
      type: Number,
      required: true,
      default: 0,
    },
    price: {
      type: Number,
      required: true,
      default: 0,
    },
    countInStock: {
      type: Number,
      required: true,
      default: 0,
    },
  },
  {
    timestamps: true,
  }
)

const Product = mongoose.model('Product', productSchema)

export default Product
