### ISSUE TITLE
How can I fix this so that it actually publishes to the database.

### ISSUE THREAD

**Issue by talmax1124** [bradtraversy/proshop_mern#126]
Hello! I have implemented orderStatus with a dropdown with component :

 https://react-bootstrap.github.io/components/dropdowns/

How can I fix orderScreen so that it pubishes that status when I click change. I changed the other files to fit this, but just need help on intgrating this on orderScreen. Here is my repo link: https://github.com/talmax1124/cduoshop

Look at the orderScreen. It should have a code for the dropdown and the top for what I was trying to do to publush it. Please tell me if there might be an error on the other files. Its all under my last commit: https://github.com/talmax1124/cduoshop/commit/d033ea43451b896b6fc12b3d3a4c3ab7133ea770

Thanks! @basir  @bradtraversy  @everyone

**Comment by basir** [comment]
hello there,
please only create issues for errors in this repo, not your own code. ask your issues in Udemy Q/A.
