### ISSUE TITLE
How to fix this when doing NPM update

### ISSUE THREAD

**Issue by talmax1124** [bradtraversy/proshop_mern#127]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   peer react@">=16.x" from @fortawesome/react-fontawesome@0.1.14
npm ERR!   node_modules/@fortawesome/react-fontawesome
npm ERR!     @fortawesome/react-fontawesome@"^0.1.14" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! react-password-mask@"^3.3.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@15.7.0
npm ERR! node_modules/react
npm ERR!   peer react@"^0.14.6 || 15.x.x" from react-password-mask@3.3.1
npm ERR!   node_modules/react-password-mask
npm ERR!     react-password-mask@"^3.3.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/carlitos/.npm/eresolve-report.txt for a full report.

**Comment by basir** [comment]
hello there,
please only create issues for errors in this repo, not your own code. ask your issues in Udemy Q/A.
