### ISSUE TITLE
Expired JWT bug

### ISSUE THREAD

**Issue by badgersmans** [bradtraversy/proshop_mern#13]
I've noticed that when the JWT expires, the frontend still stores the token in the localStorage, which doesn't make sense, as the user is still able to stay logged in, and the navbar will still show the username, but actually it should log out...

It'd be great if when the JWT expires on the backend, that the frontend would log out.

You could see this issue in action when you go to user profiles page, and wait for the JWT to time out, it will show this error message: 

![image](https://user-images.githubusercontent.com/64647433/95061894-cb8f7a80-072e-11eb-8047-1cd3fb8246a4.png)

Just a suggestion...

**Comment by bradtraversy** [comment]
Thanks, I will definitley look into this asap. Once I add a fix, I will post a note in the course as well

**Comment by badgersmans** [comment]
Thank you Brad, appreciate it!

**Comment by badgersmans** [comment]
@bradtraversy this is also related...on orders page if JWT expires, we should log out

![image](https://user-images.githubusercontent.com/64647433/95086281-e247c880-0752-11eb-8898-e87b7c96e9db.png)


but at least the error is correctly showing here

**Comment by basir** [comment]
It's been fixed. check this PR: https://github.com/bradtraversy/proshop_mern/pull/14/files
