### ISSUE TITLE
Place Order Duplicate Field Entered

### ISSUE THREAD

**Issue by hyderly** [bradtraversy/proshop_mern#130]
When I try to place a second order the "Duplicate Field Entered" Error Display. Everything all right with my order. Any other way to solve this issue?

**Comment by basir** [comment]
hello there, 
did you get this error by cloning this repo? or you have this issue in your code. if it is in your code please create an issue in Udemy Q/A. 
about duplicate error read this question please: https://stackoverflow.com/questions/42066544/how-to-avoid-duplicate-entries-in-mongoose

**Comment by hyderly** [comment]
if anyone face the same issue please follow below :
If you're using MongoAtlas, you can go to the collection -> click 'indexes' -> on the index you want to delete, click 'drop index'
