### ISSUE TITLE
Need Help With Basic React using Form component

### ISSUE THREAD

**Issue by talmax1124** [bradtraversy/proshop_mern#131]
Hello, I am trying to integrate a very simple way of coupons. Just have a variable that has a key and if that key matches then it discounts it. I am trying to implement this but the amount is not updating. Is there any sort of way to update it if it is correct am I doing it correct. If you can please visit my code in the repo link: https://github.com/talmax1124/ANNASHOPPING

I am editing it in the placeorderscreen. It might be that maybe. Anyone can help and volunteer to join a vscode share session to help me implement this. Look for the comments to see what I have done in order to accomplish this.

@bradtraversy @basir @everyone

**Comment by basir** [comment]
hello there,
as I said before please do not create issues for your own code here.
this repo is to fix the issues for the current project with current features.
also don't mention our names in the issues. we read all issues weekly.
