### ISSUE TITLE
SyntaxError: Identifier '__dirname' has already been declared

### ISSUE THREAD

**Issue by Muizuddeen** [bradtraversy/proshop_mern#132]
If i am removing this , it's working .But problem is that my image is not displaying on client side.

**Comment by basir** [comment]
hello there,
did you get this error by cloning this repo? or you have this issue in your code. if it is in your code please create an issue in Udemy Q/A not here.

about not displaying images you need to check the URL of images and the server.js. compare it with the repo code.
