### ISSUE TITLE
About CartItems

### ISSUE THREAD

**Issue by ramit0407** [bradtraversy/proshop_mern#133]
After getting logout from the page, all the items that were present in cart do not appear in the next login. How can we resolve this issue?

**Comment by basir** [comment]
hello there,
we did it intentionally because after logout we need to clear user data including selected items in the shopping cart here:
https://github.com/bradtraversy/proshop_mern/blob/master/frontend/src/actions/userActions.js#L67
if you want to keep them just remove that line.

**Comment by ramit0407** [comment]
If we remove that line  then if i login with different username, cart has products which do not belong to this username.

**Comment by talmax1124** [comment]
@basir Is there a way to save the cart items into a user's cart, so like if they move between devices they don't have to add to cart again? If so, can you provide a example, link, or PR.
