### ISSUE TITLE
❌CRITICAL PAYMENT BUG [VIDEO]: Change order status from unpaid to paid without paying for it.

### ISSUE THREAD

**Issue by kamesdev** [bradtraversy/proshop_mern#134]
I've found a bug in the code that allows making changes orders status from unpaid to paid without actually paying for it.

🎥I recorded a video that shows in detail how it works:  https://www.youtube.com/watch?v=2Jzz75MJFwg&ab_channel=kamil

**Comment by talmax1124** [comment]
Hey there @kamesdev ! Can you help out integrating another payment application such as stripe?

**Comment by basir** [comment]
hello there,
we tried to keep payment simple and easy to follow. for a fully secured payment through Paypal on the server please follow this guide:
https://developer.paypal.com/docs/archive/checkout/how-to/server-integration/

**Comment by talmax1124** [comment]
@basir I don't want to use paypal. I want to include stripe as well.
