### ISSUE TITLE
Need Help Implementing 2 things. Stripe & Multi-Image Carousel on Product Screen

### ISSUE THREAD

**Issue by talmax1124** [bradtraversy/proshop_mern#135]
Question in Udemy: https://www.udemy.com/course/mern-ecommerce/learn/lecture/22870685#questions/14625612

Hey! So I want to implement two things with some options. I have tried accomplishing this myself but as I am not experienced as much in React, this will be helpful.

first off, I want to use the Apple Pay Button from Stripe. I have used their documentation but It is not working and I can't understand what to do. I already have a stripe account, just need to make that appear.

Next, is images carousel for the product-screen. I have been getting alot of responses on to do it with arrays. I have tried this but I have not been successful in accomplishing this. I only want one image to appear on the homepage and all on the product-screen.

Thanks & If anyone can help me out, reach out to me on github: talmax1124 or email me at carlitosdiazplaza@gmail.com

**Comment by basir** [comment]
hello there,
please create issues only for bugs in the code repo. for other issues please ask it in Udemy Q/A.
