### ISSUE TITLE
Can someone help me finish integrating this feature? Look at this Udemy Q & A from this course

### ISSUE THREAD

**Issue by talmax1124** [bradtraversy/proshop_mern#139]
https://www.udemy.com/course/mern-ecommerce/learn/lecture/22870685#questions/14705018

How to implement order status

How to implement order status
0

Carlos · Lecture 91 · 20 minutes ago
Hello! I am trying to figure out how to implement Order Status. I want to have a dropdown in the orderscreen where admin only sees it and can change the status to one of 3 selections or <options> in the dropdown. I have most of the things done already but I am just stuck on the dropdown thing and how to pass it to that specific order. If anyone can check my repo code for that and help me implement the dropdown. Thanks

Refer to this image on what I refer to order status if you haven't gotten what I have said: - https://docs.xperience.io/k8/files/1835557/53706809/1/1393865229914/editing_order_selecting_order_status.png -

Something like the dropdown that changes the status

**Comment by bradtraversy** [comment]
This is not an “issue”. Please stop posting questions here. And keep your questions on the course code not on adding new features, etc

**Comment by talmax1124** [comment]
> This is not an “issue”. Please stop posting questions here. And keep your questions on the course code not on adding new features, etc

Udemy Community Not As Active
