### ISSUE TITLE
Issue with the login/register

### ISSUE THREAD

**Issue by SchickKnowsHowToKickBiatch** [bradtraversy/proshop_mern#143]
Hi, when I register a new user and log out right after it. Then after going to Login Screen I cannot switch to register. It just goes back to homescreen unless I reload the page. Does anyone know how to fix it? Thank you in advance. Have a great day!

**Comment by basir** [comment]
hello there,
we have fixed this issue in the last commit here. 
https://github.com/bradtraversy/proshop_mern/pull/43/files
you can apply this fix to your code or clone this repo and run it by following this guide to fix the issue:
https://github.com/bradtraversy/proshop_mern#usage
