### ISSUE TITLE
Error when implementing

### ISSUE THREAD

**Issue by talmax1124** [bradtraversy/proshop_mern#144]
Having an error when implementing this, what I mean by this is changing the way that when I add the component into where the <img> is and replace it and remove the img in the imports, it gives me an error.

NPM PACKAGE: https://npm.io/package/@bidlogix/react-inner-image-zoom

**Comment by basir** [comment]
hello there,
as we said before MULTIPLE TIMES, this repo is to report errors for the repo code, not yours. please follow the rules, otherwise, we have to block and report your account to Github.
