### ISSUE TITLE
I want to add order status features

### ISSUE THREAD

**Issue by himanshu-404** [bradtraversy/proshop_mern#147]
i want to add one more features that is order status update like... cancel, shipped, packed,on the way
Which is only can update by admin....i am try since 5 5
days but unable to do it.... please help me to add this feature and provide code me for it.. please

**Comment by basir** [comment]
hello there,
please ask for new features in Udemy Q/A. On this page, you can only share bugs and issues in this repo code.

**Comment by talmax1124** [comment]
@himanshu-404 I have tried doing it. I have most of it done, just need to do frontend. If you do frontend, then you can use my code.

**Comment by himanshu-404** [comment]
thanks bro...
Send me code as soon as possible
