### ISSUE TITLE
userController -> user.matchPassword is not a function

### ISSUE THREAD

**Issue by beezay** [bradtraversy/proshop_mern#148]
Hello @bradtraversy,

Hope you go through this issue to help me out.
![Screenshot 2021-05-21 150542](https://user-images.githubusercontent.com/59993093/119114656-10f68300-ba46-11eb-9d37-1bd2240b1155.jpg)

During user Auth checking, I added methods on userSchema and tried to use user.matchPassword(password) in userController.

But it throws error with user.matchPassword is not a function.

Please help on this. 

GitHub link: On Backend Branch: https://github.com/beezay/reactecommerce

//User Model
`userSchema.methods.matchPassword = async function (enteredPassword) {
  return await bcrypt.compare(enteredPassword, this.password);
};`

//User Controller
`if (user && (await user.matchPassword(password))) {
    res.json({
      _id: user._id,
      name: user.name,
      email: user.email,
      isAdmin: user.isAdmin,
      token: null,
    });
  } else {
    res.status(401);
    throw new Error("Invalid email or password");
  }`

**Comment by basir** [comment]
hello there,
please ask questions about YOUR code in udemy Q/A. this page is for issues about this repo not your code.
about the issue that you have please read this thread:
https://www.udemy.com/course/mern-ecommerce/learn/lecture/22484724#questions/12684748

**Comment by xiillii** [comment]
Hello @bradtraversy ,

I have the same problem, but I don't come from Udemy, I bought the video in Packpub

**Comment by xiillii** [comment]
Hello again,

My bad, the problem was because I was calling User.FinfOne() without await 

like
`const user =  User.findOne({ email });

  console.log(user);
  if (user && (await user.matchPassword(password))) {`

correct:
`const user = **await** User.findOne({ email });

  console.log(user);
  if (user && (await user.matchPassword(password))) {`
