### ISSUE TITLE
Log into same account again. My carts clear

### ISSUE THREAD

**Issue by Gabriel7553** [bradtraversy/proshop_mern#151]
Say you logout from your account with items in it or you're logging in from a different device so you need to log in again. My items I picked in the cart aren't there since we delete all that once we log out or logging in. How do we change that because if we just delete the line of code that make cart reset/delete. ```localStorage.removeItem("cartItems");``` How can we resolve this issue?

**Comment by basir** [comment]
if you want to keep cartItems in other devices you need to save cartItems in the server side. 
you could create a cart object in the user schema and save any change using an api in the cart in user model.
by the way, please ask errors in this repo here and for additional features ask it on udemy.
