### ISSUE TITLE
Shipping!

### ISSUE THREAD

**Issue by Gabriel7553** [bradtraversy/proshop_mern#155]
Alright I'm confused. We ask for the users shipping information on the first image but when they either use paypal or their debit or credit card information. It asks for their shipping information. What if they put different shipping information for either of them. For the debit card or credit you can make it where it says ship to billing address or just the shipping address. Won't they have more work to do. I check other websites such as this one but idk. 
![Screenshot (244)](https://user-images.githubusercontent.com/60830448/122301086-0b5d5300-ceb5-11eb-8c5c-7e5e1da07a17.png)
![Screenshot (245)](https://user-images.githubusercontent.com/60830448/122301106-0f897080-ceb5-11eb-9414-afb5332703ee.png)
![Screenshot (247)](https://user-images.githubusercontent.com/60830448/122301245-419ad280-ceb5-11eb-9f30-0881c8965083.png)

**Comment by basir** [comment]
billing and shipping data in PayPal is only for PayPal record, not the commerce website. we only get payment result form paypal and use the shipping address form to send PAYED order to the customer.
