### ISSUE TITLE
unable to access cartItems

### ISSUE THREAD

**Issue by shubhdeep123** [bradtraversy/proshop_mern#156]
unable to access cartItems
getting this error:

Unhandled Rejection (TypeError): state.cartItems.find is not a function
cartReducer
src/reducers/cartReducer.js:7
   4 | switch (action.type) {
   5 |   case CART_ADD_ITEM:
   6 |     const item = action.payload;
>  7 |     const existItem = state.cartItems.find((x) => x.product === item.product);
     | ^   8 | 
   9 |     if (existItem) {
  10 |       return {

**Comment by tanishqdaiya** [comment]
Gimme the whole code. Let's see what the error is.

**Comment by basir** [comment]
hello there,
it's not an issue with the repo code. it works. 
the issue is in your code in store.js. please ask this question in Udemy Q/A not here.
Provide your code there to take a look and fix it.
