### ISSUE TITLE
When 2 people order at the same time with the stock of 1.

### ISSUE THREAD

**Issue by Gabriel7553** [bradtraversy/proshop_mern#158]
Say 2 people are ordering at the same time. If not at the same time how about if someone adds a product with 1 in stock and 5 people already have the product in their cart. Even if someone already bought it, the people can just go to the website and it will still be in the cart. They can pay for the product and our stock will be in negatives and we] will be telling the people and refunding them. I don't know how to do this so if someone call tell me if anything or do it that would be helpful. I want it where if it's out of stock delete the product in the cart. Even when the person is at the last step of the process and all they have to do is pay. Make it where the paypal buttons are disabled. Also like a message saying "The following items are Out of Stock".

**Comment by basir** [comment]
hello there,
we did not implement inventory management in this eCommerce website. increasing and decreasing countInStock is part and a feature named "inventory management". it is on the feature list for next update of this course.
