### ISSUE TITLE
Hide Redux Devtools in production

### ISSUE THREAD

**Issue by aboubacarmsr** [bradtraversy/proshop_mern#162]
Hello,
Does anyone know how to hide the redux devtools in production ? I am not sure it's a good idea to let the users know how everything is working behind the scenes

**Comment by Chanelmermaid** [comment]
Could you help me please

**Comment by aboubacarmsr** [comment]
> Could you help me please

Do you have the same issue ? I am also waiting for someone to help

**Comment by Chanelmermaid** [comment]
Please add me LineID:Geigishapp

**Comment by alexakarpov** [comment]
@aboubacarmsr I think the place for your question is QA in Udemy =)

**Comment by basir** [comment]
hello there,
check this thread to find the answer:
https://stackoverflow.com/questions/60909402/how-to-exclude-disable-redux-devtools-in-production-build-or-disconnect
please create issues for errors in the repo not for new features or issues in your code. ask them on udemy Q/A.
