### ISSUE TITLE
Got stuck in deployment

### ISSUE THREAD

**Issue by Elham13** [bradtraversy/proshop_mern#164]
Can I host or deploy this project in godaddy?
I know how to deploy only frontend but I want to deploy both frontend and backend in the same place
Please if anybody has any idea let me know, it is really vital for me...

**Comment by basir** [comment]
hello there,
this is a regular Node.js project and can be deployed on any server that support nodejs.
please ask your question on udemy Q/A and create issue here only for errors in the repo code not your code.
