### ISSUE TITLE
Can't see any products on screen

### ISSUE THREAD

**Issue by HarshitGupta150** [bradtraversy/proshop_mern#167]
I just can't see any products after running the app on localhost 3000 , there's no error on console but it just shows a blank screen with only header and footer .Don't know how to solve this  , please help

**Comment by AmanPant777** [comment]
Give me the screenshot of redux dev tools in home page

**Comment by AmanPant777** [comment]
There is a problem with yur redux store that why products is not getting 
Help yourself with redux dev tools

**Comment by HarshitGupta150** [comment]
Thanks a lot ,I solved the issue

**Comment by AmanPant777** [comment]
Great ?Where are yu working at
