### ISSUE TITLE
decreaseQty script to decrease countinStock when user order??opinion?? 

### ISSUE THREAD

**Issue by sharafabacery** [bradtraversy/proshop_mern#17]
`const mongoose =require('mongoose')
const Product=require('../models/productModel')

module.exports=async(orderItems)=>{
 
    let idsQty=[]
    Array.prototype.forEach.call(orderItems,function(item){
        
        idsQty.push({product:mongoose.Types.ObjectId(item.product),qty:item.qty})
    })
    Array.prototype.forEach.call(idsQty,async(item)=>{
        const product=await Product.findByIdAndUpdate(item.product,{$inc:{countInStock:-1*(item.qty)}})
    })
  
}`

**Comment by basir** [comment]
it is an extra feature to handle inventory management. this feature has been noted.

**Comment by talmax1124** [comment]
> it is an extra feature to handle inventory management. this feature has been noted.

How do we know when a new video is out? I'm new to Udemy. This is my first course. @basir
