### ISSUE TITLE
Form.File tag not working in the productEditScreen

### ISSUE THREAD

**Issue by mk-aloui** [bradtraversy/proshop_mern#173]
when i use Form.File tag  to upload the image it gave me this error ( Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports)

**Comment by basir** [comment]
There may have an issue in exporting components in your project. You are rendering a component or variable that is undefined. Use console.log the values you render in the return() part of your component one by one to see which one is undefined.

**Comment by basir** [comment]
also instead of:
```
 <Form.File
                id='image-file'
                label='Choose File'
                custom
                onChange={uploadFileHandler}
              ></Form.File>
```
 use this:
```
 <Form.Control
                id='image-file'
                label='Choose File'
                type="file"
                onChange={uploadFileHandler}
              ></Form.Control>
```

**Comment by mk-aloui** [comment]
Thank you very much
