### ISSUE TITLE
Getting the Error as per the Image over on clicking up on the Add to Cart button from Product page

### ISSUE THREAD

**Issue by satheeshkumar-a** [bradtraversy/proshop_mern#174]
![image](https://user-images.githubusercontent.com/79327834/132212303-f6afcea6-d69e-4c2d-a1d2-bc7106cb0dda.png)

Help me out to solve this Issue.

Thanks in Advance.

**Comment by basir** [comment]
hello there,
please only create an issue for errors in the repo code, not your code. for yours please ask the in udemy q/a. I answer them in udemy.
