### ISSUE TITLE
Cross-Origin Read Blocking (CORB) during paypal 

### ISSUE THREAD

**Issue by killswitch99** [bradtraversy/proshop_mern#177]
I am getting this warning and my put request is also giving me a 500 error. I can see the order is goin to the database and the the ORDER_PAY_FAIL is being dispatched, causing isPaid to remain false, could this be due to CORB? and how do I remove this warning?

![Screenshot 2021-09-26 123500](https://user-images.githubusercontent.com/53596291/134791314-9c3536f4-0f6b-411f-af4b-508e8e3f6a23.png)

**Comment by basir** [comment]
hello there,
the warning isn't about the code it is from another server.
about the error message in PUT /api/orders/:id please ask it in Udemy Q/A and include the error message of this request.
