### ISSUE TITLE
Token expired

### ISSUE THREAD

**Issue by lanaarnous01** [bradtraversy/proshop_mern#179]
in postman says cannot send request 
and i cannot delete products from the products list 
please help how can i refresh my token and if i deploy the app is this still going to happen?
Thank you

**Comment by TomaszPietrzykowski** [comment]
You should probably move this thread to udemy qna. It is hard to guess remotely. You should have an "Authorization" header with string value of format: "Bearer <token>" on every request that goes through your auth middleware. Try setting it by hand with latest token you got from server upon login.

**Comment by lanaarnous01** [comment]
how can i see the latest token from the server?

**Comment by TomaszPietrzykowski** [comment]
It comes in response body from login route after successful login.

**Comment by lanaarnous01** [comment]
Sorry, I am not following, where and how exactly?

**Comment by TomaszPietrzykowski** [comment]
Consider completing the course first. That will give you understanding of how your application works. It's possible there's no quick fix if you do not know the flow of the app.

**Comment by lanaarnous01** [comment]
![postman 2](https://user-images.githubusercontent.com/93349082/139594401-71023ff5-1549-4e4b-ba4a-b080e4bd4e8c.PNG)

This is the error i keep getting on postman

**Comment by lanaarnous01** [comment]
i just want to know from where can i get the new token

**Comment by TomaszPietrzykowski** [comment]
Token is generated on the backend by authUser controller. To get one from the client you have to send POST request to /login route with valid login and password in request body. You will find a token in response body.

**Comment by lanaarnous01** [comment]
![postman 2](https://user-images.githubusercontent.com/93349082/139596657-a9e77733-9143-46d2-a6a2-b2f170ea21fd.PNG)
![api error](https://user-images.githubusercontent.com/93349082/139596663-1463a83f-2eee-4961-9c01-344f730464e2.PNG)
I did the post login but still, the error keeps occurring

**Comment by lanaarnous01** [comment]
products collection is working but not the delete products by admin 
user and auth collection none of the routes are working

**Comment by alifarukm** [comment]
Please check your bearer token from jwt.io . @lanaarnous01

**Comment by lanaarnous01** [comment]
it says invalid signature

**Comment by lanaarnous01** [comment]
i copied and paste the bearer token in authorization postman and pasted it in jwt.io and says invalid signature

**Comment by alifarukm** [comment]
Then remove last character your token.

**Comment by lanaarnous01** [comment]
i removed the last character in my token still invalid signature, what can i do

**Comment by TomaszPietrzykowski** [comment]
You don't need that header for login, you are sending credentials in body. Remove that header, hit login and get new token from backend.

**Comment by talmax1124** [comment]
Please continue this in UDEMY

**Comment by lanaarnous01** [comment]
i tried removing it but it doesnt allow me its locked
