### ISSUE TITLE
Home screen product listing

### ISSUE THREAD

**Issue by compassur2** [bradtraversy/proshop_mern#188]
How can i get product.js to put in src folder?

**Comment by Shiyadh123** [comment]
Rather, we can bring the product list to any of the components using `useSelector()`  and use it simply.

**Comment by Ali-Raza-400** [comment]
> How can i get product.js to put in src folder?

its present inside backend folder ....there is a folder data/product.js////// as you move on instructor brad move product.js to backend to push that sample products to mongodb....its little complex to follow along
