### ISSUE TITLE
issue with login & register reducer logic

### ISSUE THREAD

**Issue by AtharvRedij** [bradtraversy/proshop_mern#19]
I added code for register page along with its action & reducer. 
(specifically commit 8c75f1626f4b9143c64f73c12e07d14024e644d6)

Why do we have userInfo in both register & login reducer?

```
    case USER_LOGIN_SUCCESS:
      return { loading: false, userInfo: action.payload };
 
    case USER_REGISTER_SUCCESS:
      return { loading: false, userInfo: action.payload };
```
    
When you register, register action creator dispatches two actions

```
    dispatch({
      type: USER_REGISTER_SUCCESS,
      payload: data,
    });

    dispatch({
      type: USER_LOGIN_SUCCESS,
      payload: data,
    });
```

But when you logout, you only clear the userInfo in login reducer but userInfo in register is still there thus it won't let you go to register again. So handle user logout in register as well

```
case USER_REGISTER_FAIL:
      return { loading: false, error: action.payload };

case USER_LOGOUT:
      return {};
```

**Comment by basir** [comment]
good point. is's been noted and will be fixed in the next update.
