### ISSUE TITLE
Cast to ObjectId failed for value \"profile\" (type string) at path \"_id\" for model \"User\"

### ISSUE THREAD

**Issue by hungvalen** [bradtraversy/proshop_mern#193]
![1](https://user-images.githubusercontent.com/50736829/159148166-8bcaf0a3-180f-471b-a1ba-240870addbad.png)
![2](https://user-images.githubusercontent.com/50736829/159148168-8fd9c6ee-22f9-4724-bc7f-2a2734cc09f2.png)
![3](https://user-images.githubusercontent.com/50736829/159148169-6cb4ccb3-28c1-44b9-88f6-ec8984155719.png)
![4](https://user-images.githubusercontent.com/50736829/159148170-d3d3b6d2-9a7f-41a2-b8b6-34689c1c227e.png)

**Comment by basir** [comment]
you need to move /profile function above /:id function like this:

https://github.com/bradtraversy/proshop_mern/blob/master/backend/routes/userRoutes.js#L17

**Comment by hungvalen** [comment]
Oh thanks you
