### ISSUE TITLE
Image crash after some time

### ISSUE THREAD

**Issue by sourabhpatole** [bradtraversy/proshop_mern#196]
![Screenshot_2022-04-12-18-56-33-96](https://user-images.githubusercontent.com/51184750/162973111-edb85f06-89ca-4575-9969-2fb506f9e5e4.jpg)

**Comment by faizan15** [comment]
Try using the app in dev mode on your local machine and when you're done with uploading/updating the images, push the uploads folder on your heroku app's git repo.

Cheers ;) 🍺

**Comment by faizan15** [comment]
I'd like to know how did you overcome this problem.
Please do share your solutions over here. Ciao!

**Comment by sourabhpatole** [comment]
check the last commit
(https://github.com/sourabhpatole/shop/tree/a9ad22c493bac2780cf2a0668893a514b5325c3c)
check logs on heroku and tell me if problem face again

**Comment by faizan15** [comment]
Tested your code, problem still persists

**Comment by faizan15** [comment]
Maybe we could find an approach where the code actually utilizes the uploads/ folder in production mode

**Comment by Vedang-Danej** [comment]
To fix it you have to edit the path of the image that is sent back to the frontend. In uploadRoutes.js, in the router's post function, replace` res.send(`${req.file.path}`);`` with res.send(`\\${req.file.path}`);`
