### ISSUE TITLE
Product page does not open at the top of page

### ISSUE THREAD

**Issue by ghost** [bradtraversy/proshop_mern#20]

**Comment by harsh2124** [comment]
When a product page is opened, the page does not open at the top of the page. It opens at the mid of the page.

**Comment by bradtraversy** [comment]
It sounds like you need to add "exact" to the home route

`<Route path='/' component={HomeScreen} exact></Route>`

**Comment by harsh2124** [comment]
**Update**

This is a problem with **Firefox Browser**.

[Google Drive Link](https://drive.google.com/drive/folders/1Uil0D8i3qV07CmowIljdAZM32nyRip5A?usp=sharing)

**Comment by bradtraversy** [comment]
Oh, so the scrollbar is just pushed to the bottom automatically? That is strange. Do other sites do this? I can not replicate it.

**Comment by basir** [comment]
will work on it and let you know the solution.

**Comment by harsh2124** [comment]
Thank you @basir :D

**Comment by basir** [comment]
you are welcome @ghost
