### ISSUE TITLE
Collections being created in test database

### ISSUE THREAD

**Issue by ZohairAbbas** [bradtraversy/proshop_mern#202]
I followed the same steps but instead of data being inserted into proshop database, it's being inserted into the test

![image](https://user-images.githubusercontent.com/49277527/173351224-e715643f-0c1f-4480-bad7-33306e959b63.png)
![image](https://user-images.githubusercontent.com/49277527/173351622-8feae03a-1f6c-4646-a4b7-9b93774ec9ab.png)

**Comment by Kartikeya-Jain** [comment]
i am facing the same issue, altough it works after being created in the test database

**Comment by robregan** [comment]
it will default to the 'test' db if you don't include the name of the db you want in your connection string. 

So change `${whateverElse}bmll6.mongodb.net/` to `${whateverElse}bmll6.mongodb.net/proshop`
