### ISSUE TITLE
Beginner in React and I need help with the route function.

### ISSUE THREAD

**Issue by Dubuuuu** [bradtraversy/proshop_mern#209]
Hey guys! Anyone can help me on what is wrong with my code since every time I click on any product after using route, it just stays on the home screen. Note that my packages are the same version as the one Brad used.

**App.js**

![image](https://user-images.githubusercontent.com/88622072/194124410-ebb8a01a-e177-4fa3-9fd8-75c293b68590.png)

**HomeScreen.js**

![image](https://user-images.githubusercontent.com/88622072/194124460-54e5ae04-2d67-4fd3-bb4d-a586735f1e28.png)

**Comment by Dubuuuu** [comment]
Just found out that I have to refresh the page so that it can proceed to the ProductScreen

**Comment by dineshraj100** [comment]
i have the same doubt friend. if i click the product name, its not redirecting this issue comes after we change the <a> tag to link tag in product.js file in components section. did you found the solution?

**Comment by dineshraj100** [comment]
also if i click the product name it changes in addressbar with id but not reflecting in the page.

**Comment by JazibEqbal** [comment]
Use Link tag
