### ISSUE TITLE
user name not updating in header on user update profile

### ISSUE THREAD

**Issue by charmander-x** [bradtraversy/proshop_mern#21]
username is not being updated when i update user details i tried different things but nothing works. please tell what to do

**Comment by basir** [comment]
check if you update redux store after signin and you use it in app.js to show userInfo in the navbar.

**Comment by AtharvRedij** [comment]
This is because we have userInfo in 3 different reducers.
userLoginReducer
userRegisterReducer
userUpdateProfileReducer

When you update profile userUpdateProfileReducer updates it's userInfo.
But your Header is connected to userLoginReducer which still has old data.

**Comment by charmander-x** [comment]
so basically how can i do it -- some code will be helpful

**Comment by AtharvRedij** [comment]
I faced a similar issue regarding registration
https://github.com/bradtraversy/proshop_mern/issues/19

I haven't yet written the code to fix this problem. But you will probably need to have a single userInfo object in store that all three reducers are connected. That will solve this issue. This will require a lot of changes to redux actions & reducers

**Comment by charmander-x** [comment]
please post it here when you do so

**Comment by charmander-x** [comment]
i found the fix that's probably not the correct way but its working good 😃

in user actions after USER_UPDATE_PROFILE_SUCCESS put another dispatch({
      type: USER_LOGIN_SUCCESS,
      payload: data,
    });
    localStorage.setItem("userInfo", JSON.stringify(data));

so basically it'll set userInfo to the udpated values

**Comment by bradtraversy** [comment]
Check the latest commits. I am adding a new video to the course now explaining. It will be the last video in the Frontend Authentication section
