### ISSUE TITLE
Postman is not working

### ISSUE THREAD

**Issue by talmax1124** [bradtraversy/proshop_mern#23]
Hi, I am trying to connect to postman and it says it cannot work because of cors. Any fixes?

**Comment by basir** [comment]
send screenshot of the error please? did you use port 5000?

**Comment by talmax1124** [comment]
@basir  @bradtraversy  Here is the screenshot. https://ibb.co/fv6DHvM 

Also here is my repository link: https://github.com/talmax1124/cduoshop

**Comment by talmax1124** [comment]
@basir Everything is working fine but when I go to postman it does not show anything

**Comment by talmax1124** [comment]
> send screenshot of the error please? did you use port 5000?

Yes i did use port 5000
