### ISSUE TITLE
Project code not found

### ISSUE THREAD

**Issue by syedsimanta03** [bradtraversy/proshop_mern#25]
Each section should have completed project/code for that specific section only inside .zip file

**Comment by cdthomp1** [comment]
While your suggestion is valid, the commit history lines up with the sections in the course and can be used to see the different states of the project. Checking the commit history has helped me a bunch while going through this course.

**Comment by bradtraversy** [comment]
Please leave comments like this on Udemy, not in the repo. As cdthomp1 said and as I said in the beginning of the course, all code is in the repo and each commit has specific section code
