### ISSUE TITLE
ProductScreen is showing an empty page and an error

### ISSUE THREAD

**Issue by ryusufu** [bradtraversy/proshop_mern#31]
I'm stucked at fetching ProductScreen from backend, I'm getting an error below in my terminal.
Line 18:8:  React Hook useEffect has a missing dependency: 'match.params.id'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

![1](https://user-images.githubusercontent.com/34818816/96356680-0065df00-10ea-11eb-9559-a93b72e04a66.png)
![Untitled](https://user-images.githubusercontent.com/34818816/96356683-022fa280-10ea-11eb-804c-78a53798694e.png)

**Comment by ryusufu** [comment]
Yeah, I added the "proxy": "127.0.0.1:5000" in my package.json at the root folder

**Comment by HernanCote** [comment]
Add the “match” prop to the array of dependencies at the end of the useEffect hock, also the id is not found because that id for the product may not exists in the db

**Comment by ryusufu** [comment]
> Add the “match” prop to the array of dependencies at the end of the useEffect hock, also the id is not found because that id for the product may not exists in the db

Thanks, I can confirm it's now working. Thanks again buddy
