### ISSUE TITLE
TypeError: User.insertMany is not a function

### ISSUE THREAD

**Issue by DeeIdowu** [bradtraversy/proshop_mern#34]
<img width="316" alt="Screen Shot 2020-10-19 at 2 51 43 PM" src="https://user-images.githubusercontent.com/38046425/96498956-bb8d9580-121a-11eb-9a25-abae0b444430.png">
Currently getting the above error when trying to run the seeder.js via terminal to send data to mongodb.
Below is my code, would highly appreciate assistance:
<img width="471" alt="Screen Shot 2020-10-19 at 2 52 10 PM" src="https://user-images.githubusercontent.com/38046425/96499044-df50db80-121a-11eb-8ecc-14f62701f6d1.png">
<img width="337" alt="Screen Shot 2020-10-19 at 2 52 20 PM" src="https://user-images.githubusercontent.com/38046425/96499049-e1b33580-121a-11eb-8301-499d001ff7b4.png">

Also received errors for "Order.deleteMany is not a function" hence why I have remove method instead

**Comment by DeeIdowu** [comment]
Also received errors for "Order.deleteMany is not a function" hence why I have remove method instead.

**Comment by basir** [comment]
You are using ES5 require instead of ES6 import. Please make your code like the repo and then check it again. also update node to latest version.
