### ISSUE TITLE
404(Not Found)

### ISSUE THREAD

**Issue by Gaurav-Gaikwad-1** [bradtraversy/proshop_mern#41]
![error](https://user-images.githubusercontent.com/45882455/97048950-807fbf00-1598-11eb-9c45-d79e08189e81.png)
Even after adding proxy to .json file I m facing the error on Home Screen Page
I even tried using 'cors' pkg but it also didnt worked 
Is there something I am missing?
Here is my code snippet
![ss](https://user-images.githubusercontent.com/45882455/97049127-c8064b00-1598-11eb-93e4-4f3f2531758b.png)

**Comment by basir** [comment]
hello there
Only craete issue for errorts in this repo not for questions about the course. 
Ask questions in Udemy Q/A.
the issue is in the server.js and you did not serve this address /api/products correctly. ask it on udemy and share the repo to take a look.

**Comment by aashiqahmed98** [comment]
Hi @Gaurav-Gaikwad-1 ,did you found the solution,im too getting this error in Windows ,at starting i used in Mac,but i didnt got this error though
