### ISSUE TITLE
About the use of the classic function instead of arrow function

### ISSUE THREAD

**Issue by ThriftyWeasle** [bradtraversy/proshop_mern#45]
Hey Brad, when you created a method matchPassword in the userModel.js, you used function(enteredPassword){ } but you could do that using the arrow function (enteredPassword)=>{ }. Is this because the pointing issues of this keyword in two types of functions... If yes, could you explain it to me?

**Comment by talmax1124** [comment]
Please write this in the Q&A in Udemy. This Repo is for bug issues.
