### ISSUE TITLE
/cart/:id?  CartScreen problem

### ISSUE THREAD

**Issue by Tolgan** [bradtraversy/proshop_mern#56]
once we add a new product and redirected to cart screen , problem begins if we try to delete specific product , this happens because of:   
 useEffect(() => {
    if (productId) {
      addToCart(productId, qty);              

  just after we delete product, it is added again because of having match.params.id(productId)

**Comment by Prasadrpatil** [comment]
Solution:
In CartScreen ,do this 

 const removeFromCartHandler = (id) => {
    dispatch(removeFromCart(id))
    history.push('/cart')
  }

> once we add a new product and redirected to cart screen , problem begins if we try to delete specific product , this happens because of:
> useEffect(() => {
> if (productId) {
> addToCart(productId, qty);
> 
> just after we delete product, it is added again because of having match.params.id(productId)



> once we add a new product and redirected to cart screen , problem begins if we try to delete specific product , this happens because of:
> useEffect(() => {
> if (productId) {
> addToCart(productId, qty);
> 
> just after we delete product, it is added again because of having match.params.id(productId)

Solution:
In CartScreen ,do this 

 const removeFromCartHandler = (id) => {
    dispatch(removeFromCart(id))
    history.push('/cart')
  }

**Comment by basir** [comment]
it does not add again. if you refresh the page, yes, it adds that product to the cart again.
check the redux devtool:
![remove-from-cart](https://user-images.githubusercontent.com/2572995/98562300-23397c80-22bf-11eb-8371-91bbbe40f053.png)
