### ISSUE TITLE
Username in navbar doesn't update when updated from the profile

### ISSUE THREAD

**Issue by proghead00** [bradtraversy/proshop_mern#57]
When the username is updated via [this](http://proshopapp.herokuapp.com/profile), it gets updated on _that_ screen, but if you look at the navbar, you can see your **first** username to ever use, and it doesn't change.

Also, it doesn't require to input the password to change the username.

**Comment by bradtraversy** [comment]
This is just the demo. The issue with the header has been fixed in the actual repo and course.

I didn't make it so you had to put the password in to change the name

**Comment by proghead00** [comment]
Oh. I am following your tutorial though.

**Comment by bradtraversy** [comment]
Are you following on Udemy? because I added a note that the fix for that is in the last section.

**Comment by bradtraversy** [comment]
If not on Udemy, please let me know where

**Comment by proghead00** [comment]
Yes, I'm just starting out on Udemy, but I was checking out the original website to test the functionalities, so I had a doubt about it.
