### ISSUE TITLE
"Not Authorized, no token " Alert comes on hitting the User Profile Page

### ISSUE THREAD

**Issue by dhruvgosain95** [bradtraversy/proshop_mern#59]
![2020-11-06](https://user-images.githubusercontent.com/19353275/98334939-05071e80-202a-11eb-9b4a-363b7c66c565.png)

I am able to access the "{{URL}}/api/users/profile" with the authorization in POSTMAN but in the actual web application I am facing the issue as shown in the screen shot.

**Comment by HernanCote** [comment]
Because actually, you are not passing the token from the front end request. your action must be missing the token part when sending the request.

**Comment by Tolgan** [comment]
Not because of token , actually if you look at useractions.js carefully you will not see the axios.get("api/users/profile") , you need to create that userDetails back again ,its actually exist in backend but in frontend we want to hit that route as admin but if we are not then we get this error. you can check first parts of tutorial and recreate it .

**Comment by Tolgan** [comment]
Check your middleware in backend , probably you are not exporting admin and auth middlewares seperately

**Comment by HernanCote** [comment]
@Tolgan mate, to update your profile the admin middleware is not needed, and he already said is working from Postman so it's not something in the backend. Most likely he's not sending the token from the action before sending the PUT request.

**Comment by aorelhas** [comment]
@dhruvgosain95, make sure in your 'userActions.js' you have the headers as follow:

`    const config = {
      headers: {
        'Content-Type': "application/json",
        Authorization: `Bearer ${userInfo.token}`,
      },
    }
`

**Comment by basir** [comment]
This is not a bug of the source code. It is mistake of setting headers for the request.
please ask your questions on Udemy Q/A.
