### ISSUE TITLE
Can't access cart. "TypeError: cartItems.map is not a function"

### ISSUE THREAD

**Issue by NickSchmitt** [bradtraversy/proshop_mern#60]
I cloned your finished repo, and it's fully functioning except I receive the following error when trying to access the cart. 

```
TypeError: cartItems.map is not a function
CartScreen
src/screens/CartScreen.js:41
  38 |     Your cart is empty <Link to='/'>Go Back</Link>
  39 |   </Message>
  40 | ) : (
> 41 |   <ListGroup variant='flush'>
     | ^  42 |     {cartItems.map((item) => (
  43 |       <ListGroup.Item key={item.product}>
  44 |         <Row>
```
All I have done is npm install and add my Mongo URI to .env. 

Any idea why I might be running into this error?

**Comment by aorelhas** [comment]
Could you try to use a postman and hit this route? get(`/api/products/${id}`);

**Comment by basir** [comment]
I clone the repo and set the .env file and it works.
please open an Incognito window and try again.
I guess there is value for `localStorage.getItem('cartItems')` here:

store.js
```
const cartItemsFromStorage = localStorage.getItem('cartItems')
  ? JSON.parse(localStorage.getItem('cartItems'))
  : []
```

**Comment by talmax1124** [comment]
@basir  I have tried cloning the repo but it gives me a error and I set up the repo's and everything. Is there another command or something I'm doing wrong?

**Comment by basir** [comment]
What error do you get? Share screenshot please

**Comment by NickSchmitt** [comment]
> I clone the repo and set the .env file and it works.
> please open an Incognito window and try again.
> I guess there is value for `localStorage.getItem('cartItems')` here:
> 
> store.js
> 
> ```
> const cartItemsFromStorage = localStorage.getItem('cartItems')
>   ? JSON.parse(localStorage.getItem('cartItems'))
>   : []
> ```

Oh wow, it works in incognito! Do you know why that is? How do I make it work without going on incognito?

**Comment by NickSchmitt** [comment]
In incognito browser, Storage.cartItems is _correctly_ an array of objects:

`cartItems: "[{"product":"5fa8a16...etc`

In my browser, Storage.cartItems is _incorrectly_ an object of objects:

`cartItems: "{"item":{"product":"5fa34c1e`

Is this a bug in _my_ project code's localStorage that has persisted over to your finished repo's localStorage?

**Comment by ShwetaSachan** [comment]
TypeError: cartItems.map is not a function

**Comment by ShwetaSachan** [comment]
> I cloned your finished repo, and it's fully functioning except I receive the following error when trying to access the cart.
> 
> ```
> TypeError: cartItems.map is not a function
> CartScreen
> src/screens/CartScreen.js:41
>   38 |     Your cart is empty <Link to='/'>Go Back</Link>
>   39 |   </Message>
>   40 | ) : (
> > 41 |   <ListGroup variant='flush'>
>      | ^  42 |     {cartItems.map((item) => (
>   43 |       <ListGroup.Item key={item.product}>
>   44 |         <Row>
> ```
> 
> All I have done is npm install and add my Mongo URI to .env.
> 
> Any idea why I might be running into this error?

TypeError: cartItems.map is not a function

**Comment by ShwetaSachan** [comment]
TypeError: cartItems.map is not a function
