### ISSUE TITLE
sameSite=none; secure

### ISSUE THREAD

**Issue by AdamAksel** [bradtraversy/proshop_mern#61]
When using PayPal it refuses to connect and says the cookies have the wrong settings.

**Comment by aorelhas** [comment]
Did you make some changes to the original repo? or you just fork > clone > and install dependencies?

**Comment by basir** [comment]
I clone the repo and did not get this error. try with incognito window please.
if you check the demo website of this repo here: https://proshopapp.herokuapp.com/
you should not get this error.
Please ask your questions on udemy Q/A and when you make sure that there is a obvious bug, report here.

**Comment by AdamAksel** [comment]
I have just been coding along, so maybe i missed something, ill try the incognito window.

Thank you.
