### ISSUE TITLE
Losing details about User Orders when Admin delete User

### ISSUE THREAD

**Issue by aorelhas** [bradtraversy/proshop_mern#63]
When an admin deletes a user with orders when seeing the orders we lose the history about what users make the purchase. 

It should show the users information about what name make the purchase even if the users get deleted. 
<img width="1177" alt="Screenshot 2020-11-10 at 17 19 16" src="https://user-images.githubusercontent.com/15917130/98708323-f0ec5580-2378-11eb-949b-1f594d0b52eb.png">
<img width="1177" alt="Screenshot 2020-11-10 at 17 19 24" src="https://user-images.githubusercontent.com/15917130/98708330-f2b61900-2378-11eb-9e6d-f1339c511e6d.png">
<img width="1177" alt="Screenshot 2020-11-10 at 17 19 35" src="https://user-images.githubusercontent.com/15917130/98708333-f34eaf80-2378-11eb-954d-26ca49b10cd5.png">

**Comment by basir** [comment]
yes. you are right. we tried to make this e-commerce as simple as possible. for the real-world scenarios it is much better to set a isDeleted flag to all records and set them to true when you delete a record.
It's been noted.
