### ISSUE TITLE
TypeError: Cannot read property 'orderItems' of undefined

### ISSUE THREAD

**Issue by jeanyuss** [bradtraversy/proshop_mern#70]
Hey so I'm working on the admin part of the project now. Everything seems to work up until this point and I keep getting this error where 'orderItems' is undefined in the orderScreen.js when I try to access '/admin/userList'
<img width="696" alt="Screen Shot 2020-11-17 at 12 54 02 PM" src="https://user-images.githubusercontent.com/57467866/99428823-23e09d00-28d5-11eb-8f06-f67cd50369cb.png">

However, I tried to diagnose this problem and this is what I get in the console:
<img width="393" alt="Screen Shot 2020-11-17 at 12 59 50 PM" src="https://user-images.githubusercontent.com/57467866/99428881-39ee5d80-28d5-11eb-9282-66877959d4dd.png">

Any help would be appreciated!

**Comment by RamiAly** [comment]
You should instantiate orderItems in the state of your reducer, so that it becomes "defined"

**Comment by jeanyuss** [comment]
Is this what you mean? Because I've had this in my reducer.
<img width="504" alt="Screen Shot 2020-11-17 at 1 56 34 PM" src="https://user-images.githubusercontent.com/57467866/99434416-c51f2180-28dc-11eb-823a-65560716a3b3.png">

**Comment by jeanyuss** [comment]
Nevermind, I figured it out! It wasn't the state, but thanks for the reply!

**Comment by Dunit05** [comment]
can you explain how you fixed it, I have the same problem but cant fixes it?

**Comment by jasonchg** [comment]
Maybe try to put,  orderItems && orderItems.reduce. the error should gone. It's work for me.

**Comment by Dunit05** [comment]
sorry I am new to react, so do I put this in the orderScreen.js file with the 
order.itemsPrice = addDecimals(
      order.orderItems.reduce((acc, item) => acc + item.price * item.qty, 0)
    );
