### ISSUE TITLE
Hey, I am getting this weird error and I can't figure out what's the issue.

### ISSUE THREAD

**Issue by kiranojhanp** [bradtraversy/proshop_mern#77]
Screenshot:
![image](https://user-images.githubusercontent.com/54209728/100431137-d5df4c80-30bf-11eb-9d5e-8be1d711c690.png)

Github: 
[Repo](https://github.com/kiranojhanp/react-ecommerce.git)

**Comment by talmax1124** [comment]
This is for bugs only. Please ask in Q&A. 

Anyways copy this:

  const dispatch = useDispatch()

  const productList = useSelector((state) => state.productList)
  const { loading, error, products, page, pages } = productList

  useEffect(() => {
    dispatch(listProducts())
  }, [dispatch])

**Comment by talmax1124** [comment]
Look at the repo as well. https://github.com/bradtraversy/proshop_mern

**Comment by basir** [comment]
> Screenshot:
> ![image](https://user-images.githubusercontent.com/54209728/100431137-d5df4c80-30bf-11eb-9d5e-8be1d711c690.png)
> 
> Github:
> [Repo](https://github.com/kiranojhanp/react-ecommerce.git)

when you get this error:
Action must be plain text, it means you did not add redux-thunk middleware to the redux store.
check store.js
https://github.com/bradtraversy/proshop_mern/blob/master/frontend/src/store.jshttps://github.com/bradtraversy/proshop_mern/blob/master/frontend/src/store.js

also please ask your errors and questions on udemy Q/A. Create an issue here only if you found an error in this code, not yours.

**Comment by kiranojhanp** [comment]
Yeah I should've sent on udemy. My bad!! Thanks for the help. The issue was I forgot an arrow function in productAction. changed `export const listProducts =  async (dispatch) => {` to `export const listProducts = () => async (dispatch) => {` which solved it.
