### ISSUE TITLE
Schema hasn't been registered for model "User". Use mongoose.model(name, schema)

### ISSUE THREAD

**Issue by Dunit05** [bradtraversy/proshop_mern#78]
I have edited the schema but nothing seems to be working 
![Screenshot 2020-11-30 211755](https://user-images.githubusercontent.com/52969440/100689020-a182bf00-3351-11eb-9314-6c7db244f049.jpg)

**Comment by basir** [comment]
hello there,
It is not an error for this repo. please ask your questions and issues on Q/A not here. 
Here is for errors in this code.
