### ISSUE TITLE
cartscreen Qty value doesn't update in screen but does in state

### ISSUE THREAD

**Issue by liadbelad** [bradtraversy/proshop_mern#82]
Hey I got a weird bug I can't find how to solve 
When I change the qty from the cart screen it doesn't change the value but does changing the state 

I even copy the full code of the CartScreen and this got the issue 

Here's the code part of this page 
{cartItems.map((item) => (
              <ListGroup.Item key={item.product}>
                <Row>
                  <Col md={2}>
                    <Image src={item.image} alt={item.name} fluid rounded />
                  </Col>
                  <Col md={3}>
                    <Link to={`/product/${item.product}`}>{item.name}</Link>
                  </Col>
                  <Col md={2}>${item.price}</Col>
                  <Col md={2}>
                    <Form.Control
                      as='select'
                      value={item.qty}
                      onChange={(e) =>
                        dispatch(
                          addToCart(item.product, Number(e.target.value))
                        )
                      }
                    >
                      {[...Array(item.countInStock).keys()].map((x) => (
                        <option key={x + 1} value={x + 1}>
                          {x + 1}
                        </option>
                      ))}
                    </Form.Control>
                  </Col>
                  <Col md={2}>
                    <Button
                      type='button'
                      variant='light'
                      onClick={() => removeFromCartHandler(item.product)}
                    >
                      <i className='fas fa-trash'></i>
                    </Button>
                  </Col>
                </Row>
              </ListGroup.Item>
            ))}`

Photo is here: 
https://ibb.co/t2mdCCD

**Comment by liadbelad** [comment]
I figured it out!

**Comment by MarkVed17** [comment]
> I figured it out!

How?
