### ISSUE TITLE
How to get data back from the data:import

### ISSUE THREAD

**Issue by talmax1124** [bradtraversy/proshop_mern#83]
Hello, I was talking to this fellow to implement the Google Sign-In. He told me that it would not erase anything that I already had, apparently when I tried to implement it, it was false. It ERASED everything that I had.

https://www.udemy.com/course/mern-ecommerce/learn/#questions/13188118

What can I do to get the data back or is there a way to make a backup of the data that way when I make a change, it does not affect everything?

@basir @bradtraversy

**Comment by basir** [comment]
hello there
in seeder.js all data get removed in this line:
https://github.com/bradtraversy/proshop_mern/blob/master/backend/seeder.js#L17
you can't get them back anymore.
To have a backup on your next database on atlas you can use this service:
https://docs.atlas.mongodb.com/backup/cloud-backup/overview

**Comment by talmax1124** [comment]
@basir Is there a way so that when I do data:import the products do not get removed
