### ISSUE TITLE
There should be at least one admin.

### ISSUE THREAD

**Issue by zeeshanhshaheen** [bradtraversy/proshop_mern#87]
Hello brad,
I hope you are doing well. I think there's a bug in the app. There should be at least one admin for this app.

When we login as an admin and in users there's a user named admin. If we uncheck make admin option and save, then there is no admin for this app. Now no one can change or create a product.

I suggest there should be at least one admin and make admin option should be disabled for the current first admin.
Thanks and regards,

**Comment by basir** [comment]
hello there
thanks for the comment.
yes, it could be better to prevent deleting admin user.
you can implement that by adding this condition in userContoller.js
const admins = await User.find({isAdmin: true});
if(admins.length ===0) {
throw Error("admin user can't be deleted");
}

**Comment by talmax1124** [comment]
@basir What file would we implement this in?

**Comment by talmax1124** [comment]
@basir Would we need to put it inside of any of the other const like the auth user or just seperate from the rest?
