### ISSUE TITLE
A bug with search box

### ISSUE THREAD

**Issue by liadbelad** [bradtraversy/proshop_mern#89]
Hey there !
I found a bug while trying to search 2 or more words with the search box component
For exampe if I type some words of a product's title like 'CANNON 80D' - show no results even though it is exist 

Another bug in this component is when I try to search one word with few spaces before/after - looks like the trim isn't working propely in this case and shows no results also for this search 

Any1 managed to solve that  ?

**Comment by basir** [comment]
1. make sure you typed it correctly. check this out: https://proshopapp.herokuapp.com/search/Sony%20Playstation
it works.
also, you can use encodeURI() to encode query string in the URL of API. https://www.w3schools.com/jsref/jsref_encodeuri.asp

2. For trim you can use use trim method like this: https://www.w3schools.com/jsref/jsref_trim_string.asp

**Comment by aashiqahmed98** [comment]
Use trim in the server side,i mean the controller in listProducts


const searchQuery = (req.query.keyword).trim()

  const keyword = searchQuery ? {
    name: {
      $regex: searchQuery,
      $options: 'i'
    }
