### ISSUE TITLE
Route changes, but only one order can be seen

### ISSUE THREAD

**Issue by dziugaspeciulevicius** [bradtraversy/proshop_mern#9]
Lets say I made few orders just like in the example below:

![image](https://user-images.githubusercontent.com/43075730/95010637-8fc3ba80-0633-11eb-9ba7-21199175d759.png)

If I want to pay for other orders and click on a random one that's not paid, route changes, but the program still brings me to the first order made. In this example I clicked on the last one, and it brought me back to the one I first made: 

 <div align="center">

![image](https://user-images.githubusercontent.com/43075730/95010897-8dfaf680-0635-11eb-98c1-ff84a519fd39.png)

![image](https://user-images.githubusercontent.com/43075730/95010691-18daf180-0634-11eb-8465-d6f2acc6ca18.png)

</div>

**Comment by basir** [comment]
OrderScreen.js Line 66:
    if (!order || successPay || successDeliver) {
replace with:
    if (!order  || successPay || successDeliver || (order && order._id !== orderId)) {

**Comment by bradtraversy** [comment]
Add the condition in Basir's response. it will make sure the order matches the one in the URL. I will add a note for this
