### ISSUE TITLE
Heroku Problems

### ISSUE THREAD

**Issue by talmax1124** [bradtraversy/proshop_mern#93]
Hi, I have been at this for the last 3 hours. I have been installing dependencies and everything. I can't get heroku to stop saying build failed because of the script below. Anyone has any fixes? You can view my repo by going to my profile & look for talmax1124/shop

@basir @bradtraversy 

This is what the output for heroku shows:

> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       NODE_VERBOSE=false
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 12.x...
       Downloading and installing node 12.20.1...
       Using default npm version: 6.14.10
       
-----> Restoring cache
       Cached directories were not restored due to a change in version of node, npm, yarn or stack
       Module installation may take longer for this build
       
-----> Installing dependencies
       Installing node modules
       
       > core-js@2.6.12 postinstall /tmp/build_3c1a263c_/node_modules/babel-runtime/node_modules/core-js
       > node -e "try{require('./postinstall')}catch(e){}"
       
       
       > ejs@2.7.4 postinstall /tmp/build_3c1a263c_/node_modules/ejs
       > node ./postinstall.js
       
       
       > fsevents@1.2.13 install /tmp/build_3c1a263c_/node_modules/webpack-dev-server/node_modules/fsevents
       > node install.js
       
       
       Skipping 'fsevents' build as platform linux is not supported
       
       > fsevents@1.2.13 install /tmp/build_3c1a263c_/node_modules/watchpack-chokidar2/node_modules/fsevents
       > node install.js
       
       
       Skipping 'fsevents' build as platform linux is not supported
       
       > core-js@3.8.2 postinstall /tmp/build_3c1a263c_/node_modules/core-js
       > node -e "try{require('./postinstall')}catch(e){}"
       
       
       > core-js-pure@3.8.2 postinstall /tmp/build_3c1a263c_/node_modules/core-js-pure
       > node -e "try{require('./postinstall')}catch(e){}"
       
       
       > core-js@3.6.5 postinstall /tmp/build_3c1a263c_/node_modules/cloudinary/node_modules/core-js
       > node -e "try{require('./postinstall')}catch(e){}"
       
       
       > nodemon@2.0.7 postinstall /tmp/build_3c1a263c_/node_modules/nodemon
       > node bin/postinstall || exit 0
       
       Love nodemon? You can now support the project via the open collective:
        > https://opencollective.com/nodemon/donate
       
       added 2103 packages in 29.561s
       
-----> Build
       Running heroku-postbuild
       
       > creative-duo-shop@1.0.0 heroku-postbuild /tmp/build_3c1a263c_
       > NPM_CONFIG_PRODUCTION=false npm install --prefix frontend && npm run build --prefix frontend
       
       
       > ejs@2.7.4 postinstall /tmp/build_3c1a263c_/frontend/node_modules/ejs
       > node ./postinstall.js
       
       added 689 packages from 221 contributors and audited 2170 packages in 24.522s
       
       129 packages are looking for funding
         run `npm fund` for details
       
       found 0 vulnerabilities
       
       
       > frontend@0.1.0 build /tmp/build_3c1a263c_/frontend
       > react-scripts build
       
internal/modules/cjs/loader.js:818
  throw err;
  ^
Error: Cannot find module '../utils'
Require stack:
- /tmp/build_3c1a263c_/frontend/node_modules/fast-glob/out/managers/tasks.js
- /tmp/build_3c1a263c_/frontend/node_modules/fast-glob/out/index.js
- /tmp/build_3c1a263c_/frontend/node_modules/react-dev-utils/node_modules/globby/index.js
- /tmp/build_3c1a263c_/frontend/node_modules/react-dev-utils/globby.js
- /tmp/build_3c1a263c_/frontend/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js
- /tmp/build_3c1a263c_/frontend/node_modules/react-scripts/scripts/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/tmp/build_3c1a263c_/frontend/node_modules/fast-glob/out/managers/tasks.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/build_3c1a263c_/frontend/node_modules/fast-glob/out/managers/tasks.js',
    '/tmp/build_3c1a263c_/frontend/node_modules/fast-glob/out/index.js',
    '/tmp/build_3c1a263c_/frontend/node_modules/react-dev-utils/node_modules/globby/index.js',
    '/tmp/build_3c1a263c_/frontend/node_modules/react-dev-utils/globby.js',
    '/tmp/build_3c1a263c_/frontend/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js',
    '/tmp/build_3c1a263c_/frontend/node_modules/react-scripts/scripts/build.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.ulE5s/_logs/2021-01-12T00_00_05_407Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! creative-duo-shop@1.0.0 heroku-postbuild: `NPM_CONFIG_PRODUCTION=false npm install --prefix frontend && npm run build --prefix frontend`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the creative-duo-shop@1.0.0 heroku-postbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.ulE5s/_logs/2021-01-12T00_00_05_430Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by basir** [comment]
hello there,
it is not a bug in the repo.
please ask it in Udemy Q/A.
about the error please check this line:
Error: Cannot find module '../utils'
it means either you do not have utils or the naming is wrong in terms of case sensitivity.
