### ISSUE TITLE
PayPal capture

### ISSUE THREAD

**Issue by OmarAhmed3012** [bradtraversy/proshop_mern#94]
It keeps showing me 400 bad request when I try to pay throw PayPal after the payment process is done and the pop up close
![IMG_20210114_225655.jpg](https://user-images.githubusercontent.com/43046273/104648488-deb1cf00-56bb-11eb-9e2e-dd6a18241eb7.jpg)

**Comment by basir** [comment]
hello there
it is not error in the repo. please ask your questions in Udemy.
the error code is 400. it means you did not supply correct data like this:
https://github.com/bradtraversy/proshop_mern/blob/master/frontend/src/screens/OrderScreen.js#L204
also make sure the backend code for pay order is like this:
https://github.com/bradtraversy/proshop_mern/blob/master/backend/controllers/orderController.js#L60
