### ISSUE TITLE
Font-awesome icons doesn't display

### ISSUE THREAD

**Issue by B4xAbhishek** [bradtraversy/proshop_mern#97]
The font icon used in the project is not displaying either stars or the cart or user icon. I have added the link in index.js and using the correct format but it doesn't work. Please check.

**Comment by basir** [comment]
hello there,
it is not an error in the repo.
you can clone this repo and run it on your computer. It works and shows icons.

https://github.com/bradtraversy/proshop_mern/

compare it with your code.
